name: Build and Upload One GUI Image as Artifact

on:
  workflow_dispatch:
    inputs:
      gui:
        description: "Choose Desktop Environment"
        required: true
        type: choice
        options:
          - xfce
          - kde
          - gnome
          - mate
          - cinnamon
          - lxqt
      protocol:
        description: "Choose Remote Protocol"
        required: true
        type: choice
        options:
          - vnc
          - xrdp

jobs:
  build-upload:
    runs-on: ubuntu-latest
    env:
      TAG: ${{ github.event.inputs.gui }}-${{ github.event.inputs.protocol }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |
          GUI="${{ github.event.inputs.gui }}"
          PROTO="${{ github.event.inputs.protocol }}"
          TAG="$GUI-$PROTO"

          if [ "$GUI" = "xfce" ]; then DE="xfce4"
          elif [ "$GUI" = "kde" ]; then DE="kde-plasma-desktop"
          elif [ "$GUI" = "gnome" ]; then DE="ubuntu-desktop"
          elif [ "$GUI" = "mate" ]; then DE="mate-desktop-environment"
          elif [ "$GUI" = "cinnamon" ]; then DE="cinnamon"
          elif [ "$GUI" = "lxqt" ]; then DE="lxqt"
          else echo "Unknown GUI: $GUI" && exit 1; fi

          if [ "$PROTO" = "vnc" ]; then SRV="tigervnc-standalone-server"
          elif [ "$PROTO" = "xrdp" ]; then SRV="xrdp"
          else echo "Unknown protocol: $PROTO" && exit 1; fi

          echo "FROM ubuntu:22.04
          ENV DEBIAN_FRONTEND=noninteractive
          RUN apt-get update && \
              apt-get install -y $DE $SRV sudo && \
              useradd -m linuxuser && \
              echo 'linuxuser:Ab@1234' | chpasswd && \
              echo 'root:Ab@1234' | chpasswd && \
              usermod -aG sudo linuxuser

          COPY entrypoint.sh /entrypoint.sh
          RUN chmod +x /entrypoint.sh

          ENTRYPOINT [\"/entrypoint.sh\"]" > Dockerfile

          echo "#!/bin/bash
          set -e

          if [ \"\$1\" = \"vnc\" ]; then
            su - linuxuser -c \"vncserver :1 -geometry 1280x720\"
          elif [ \"\$1\" = \"xrdp\" ]; then
            service xrdp start || xrdp-sesman &
          fi

          tail -f /dev/null" > entrypoint.sh

          docker build -t "$TAG" .

      - name: Save Docker image as TAR
        run: |
          mkdir -p output
          docker save "$TAG" -o "output/$TAG.tar"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.TAG }}
          path: output/${{ env.TAG }}.tar
