name: Build and Upload One GUI Image

on:
  workflow_dispatch:
    inputs:
      gui:
        description: "Choose Desktop Environment"
        required: true
        type: choice
        options:
          - xfce
          - kde
          - gnome
      protocol:
        description: "Choose Remote Protocol"
        required: true
        type: choice
        options:
          - vnc
          - xrdp

jobs:
  build-upload:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build selected desktop image
      run: |
        GUI=${{ github.event.inputs.gui }}
        PROTO=${{ github.event.inputs.protocol }}
        TAG="$GUI-$PROTO"

        # Select packages based on combo
        if [ "$GUI" = "xfce" ]; then DE="xfce4"
        elif [ "$GUI" = "kde" ]; then DE="kde-plasma-desktop"
        elif [ "$GUI" = "gnome" ]; then DE="ubuntu-desktop"
        fi

        if [ "$PROTO" = "vnc" ]; then SERVER="tigervnc-standalone-server"; PORT=5901
        else SERVER="xrdp"; PORT=3389
        fi

        echo "Building image: $TAG with $DE and $SERVER"

        echo "
        FROM ubuntu:22.04
        ENV DEBIAN_FRONTEND=noninteractive
        RUN apt-get update && \
            apt-get install -y $DE $SERVER && \
            apt-get clean && rm -rf /var/lib/apt/lists/*
        CMD [\"tail\", \"-f\", \"/dev/null\"]
        " | docker build -t "$TAG" -f - .

    - name: Save image as TAR
      run: |
        TAG=${{ github.event.inputs.gui }}-${{ github.event.inputs.protocol }}
        mkdir -p output
        docker save "$TAG" -o "output/$TAG.tar"

    - name: Upload TAR to GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        name: "gui-images"
        tag_name: gui-images
        files: output/*.tar
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
