name: Build and Commit Desktop Images

on:
  workflow_dispatch:

jobs:
  build-and-commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up Docker
      uses: docker/setup-buildx-action@v3

    - name: Make tars directory
      run: mkdir -p tars

    - name: Build all images and export tars
      run: |
        declare -A combos=(
          [xfce-vnc]="xfce4 tigervnc-standalone-server"
          [xfce-xrdp]="xfce4 xrdp"
          [kde-vnc]="kde-plasma-desktop tigervnc-standalone-server"
          [kde-xrdp]="kde-plasma-desktop xrdp"
          [gnome-vnc]="ubuntu-desktop tigervnc-standalone-server"
          [gnome-xrdp]="ubuntu-desktop xrdp"
        )

        for combo in "${!combos[@]}"; do
          echo "Building image: $combo"
          packages="${combos[$combo]}"

          echo "
          FROM ubuntu:22.04
          ENV DEBIAN_FRONTEND=noninteractive
          RUN apt-get update && \
              apt-get install -y $packages && \
              apt-get clean && rm -rf /var/lib/apt/lists/*
          CMD [\"tail\", \"-f\", \"/dev/null\"]
          " | docker build -t "$combo" -f - .

          echo "Saving image $combo to tars/$combo.tar"
          docker save "$combo" -o "tars/$combo.tar"
        done

    - name: Commit TARs to repository
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add tars/*.tar
        git commit -m "Add prebuilt desktop images as tarballs"
        git push
        
