name: Build and Commit One GUI Image via LFS

on:
  workflow_dispatch:
    inputs:
      gui:
        description: "Choose Desktop Environment"
        required: true
        type: choice
        options:
          - xfce
          - kde
          - gnome
          - mate
          - cinnamon
          - lxqt
      protocol:
        description: "Choose Remote Protocol"
        required: true
        type: choice
        options:
          - vnc
          - xrdp

jobs:
  build-commit:
    runs-on: ubuntu-latest
    env:
      TAG: ${{ github.event.inputs.gui }}-${{ github.event.inputs.protocol }}

    steps:
      - name: Checkout repository with LFS
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Set up Git LFS
        run: git lfs install

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |
          GUI="${{ github.event.inputs.gui }}"
          PROTO="${{ github.event.inputs.protocol }}"
          TAG="$GUI-$PROTO"

          if [ "$GUI" = "xfce" ]; then DE="xfce4"
          elif [ "$GUI" = "kde" ]; then DE="kde-plasma-desktop"
          elif [ "$GUI" = "gnome" ]; then DE="ubuntu-desktop"
          elif [ "$GUI" = "mate" ]; then DE="mate-desktop-environment"
          elif [ "$GUI" = "cinnamon" ]; then DE="cinnamon"
          elif [ "$GUI" = "lxqt" ]; then DE="lxqt"
          else
            echo "Unknown GUI: $GUI"
            exit 1
          fi

          if [ "$PROTO" = "vnc" ]; then SRV="tigervnc-standalone-server"
          elif [ "$PROTO" = "xrdp" ]; then SRV="xrdp"
          else
            echo "Unknown Protocol: $PROTO"
            exit 1
          fi

          echo "Building image: $TAG with $DE and $SRV"

          # Write Dockerfile using here-document
          cat <<EOF > Dockerfile
          FROM ubuntu:22.04
          ENV DEBIAN_FRONTEND=noninteractive
          RUN apt-get update && \\
              apt-get install -y $DE $SRV sudo && \\
              useradd -m linuxuser && \\
              echo 'linuxuser:Ab@1234' | chpasswd && \\
              echo 'root:Ab@1234' | chpasswd && \\
              usermod -aG sudo linuxuser
          COPY entrypoint.sh /entrypoint.sh
          RUN chmod +x /entrypoint.sh
          ENTRYPOINT ["/entrypoint.sh"]
          EOF

          # Write entrypoint.sh using here-document
          cat <<'EOF' > entrypoint.sh
          #!/bin/bash
          set -e
          if [ "$1" = "vnc" ]; then
            su - linuxuser -c "vncserver :1 -geometry 1280x720"
          elif [ "$1" = "xrdp" ]; then
            service xrdp start || (xrdp-sesman &)
          fi
          tail -f /dev/null
          EOF

          docker build -t "$TAG" .

      - name: Save Docker image as tarball
        run: |
          mkdir -p tars
          docker save "$TAG" -o "tars/$TAG.tar"

      - name: Track tarball with Git LFS and commit
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git lfs track "tars/$TAG.tar"
          git add .gitattributes tars/$TAG.tar
          git commit -m "Add Docker image $TAG as LFS object"
          git push
