name: Run GUI Image with Bore Tunnel

on:
  workflow_dispatch:
    inputs:
      gui:
        description: "Select Desktop Environment"
        required: true
        type: choice
        options:
          - xfce
          - kde
          - gnome
          - mate
          - cinnamon
          - lxqt
      protocol:
        description: "Select Remote Protocol"
        required: true
        type: choice
        options:
          - vnc
          - xrdp

jobs:
  run-container:
    runs-on: ubuntu-latest
    env:
      TAG: ${{ github.event.inputs.gui }}-${{ github.event.inputs.protocol }}

    steps:
      - name: Checkout Repo with LFS
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Install Docker
        uses: docker/setup-buildx-action@v3

      - name: Load Docker image from tar
        run: |
          docker load -i tars/${{ env.TAG }}.tar

      - name: Run container with correct port and service
        run: |
          PORT=$([ "${{ github.event.inputs.protocol }}" = "vnc" ] && echo 5901 || echo 3389)
          docker run -d --rm --name gui-runner -p $PORT:$PORT $TAG ${{ github.event.inputs.protocol }}
          echo "Launched container $TAG on port $PORT"

      - name: Install Bore
        run: npm install -g bore

      - name: Tunnel with Bore
        run: |
          PORT=$([ "${{ github.event.inputs.protocol }}" = "vnc" ] && echo 5901 || echo 3389)
          nohup bore --port $PORT --to bore.pub > bore.log 2>&1 &
